export const FOCUS_MODE_ADD_TOPIC_REFERENCE = 'FOCUS_MODE_ADD_TOPIC_REFERENCE';
export const OP_TYPE_START_ADD_TOPIC_REFERENCE = 'OP_TYPE_START_ADD_TOPIC_REFERENCE';
export const BLOCK_TYPE_REFERENCE = 'REFERENCE';
