export const FOCUS_MODE_SET_REFERENCE_TOPICS =
  'FOCUS_MODE_SET_REFERENCE_TOPICS';
// 添加引用的Topic
export const OP_TYPE_START_SET_REFERENCE_TOPICS =
  'OP_TYPE_START_SET_REFERENCE_TOPICS';
export const OP_TYPE_SET_REFERENCE_TOPICS = 'OP_TYPE_SET_REFERENCE_TOPICS';
export const BLOCK_TYPE_REFERENCE_TOPIC = 'REFERENCE_TOPIC';
// export const BLOCK_TYPE_REFERENCED_TOPIC = 'REFERENCED_TOPIC';
