export const FOCUS_MODE_SET_REFERENCE_TOPICS =
  'FOCUS_MODE_SET_REFERENCE_TOPICS';
// 添加引用的Topic
export const OP_TYPE_START_SET_REFERENCE_TOPICS =
  'OP_TYPE_START_SET_REFERENCE_TOPICS';
export const OP_TYPE_SET_REFERENCE_TOPICS = 'OP_TYPE_SET_REFERENCE_TOPICS';

export const EXT_DATA_KEY_TOPIC_REFERENCE = 'TOPIC_REFERENCE';

export const EXT_KEY_TOPIC_REFERENCE = 'EXT_KEY_TOPIC_REFERENCE';
