export function contentRefKey(key) {
  return `content-${key}`;
}

export function contentEditorRefKey(key) {
  return `content-editor-${key}`;
}

export function descEditorRefKey(key) {
  return `desc-editor-${key}`;
}

export function topicWidgetRefKey(key) {
  return `topic-widget-${key}`;
}
export function topicWidgetRootRefKey(key) {
  return `topic-widget-root-${key}`;
}

export function topicNodeRefKey(key) {
  return `topic-node-${key}`;
}

export function linksRefKey(key) {
  return `links-${key}`;
}

export function linksSvgRefKey(key) {
  return `links-svg-${key}`;
}

export function collapseRefKey(key) {
  return `collapse-${key}`;
}

export function dropAreaRefKey(key, dir) {
  return `dropArea-${dir}-${key}`;
}

export const RefKey = {
  SHEET_ROOT_KEY: 'SHEET-ROOT-',
  DRAG_SCROLL_WIDGET_KEY: 'DRAG-SCROLL-WIDGET-',
  SVG_HIGHLIGHT_KEY: 'SVG-HIGHLIGHT-',
  FOCUS_HIGHLIGHT_KEY: 'FOCUS-HIGHLIGHT-',
  DROP_EFFECT_KEY: 'DROP-EFFECT-',
  SVG_DROP_EFFECT_KEY: 'SVG-DROP-EFFECT-',
  NODE_LAYER: 'NODE-LAYER-'
};
export const EventKey = {
  CENTER_ROOT_TOPIC: 'CENTER_ROOT_TOPIC'
};

export const PropKey = {
  DIAGRAM_CUSTOMIZE_BASE_Z_INDEX: 'DIAGRAM_CUSTOMIZE_BASE_Z_INDEX',
  TOPIC_CONTEXT_MENU_ENABLED: 'TOPIC_CONTEXT_MENU_ENABLED',
  TOPIC_TITLE: 'TOPIC_TITLE',
  DRAG_DROP_STATE: 'DRAG_DROP_STATE',
  RIGHT_TOP_PANEL_STATE: 'RIGHT_TOP_PANEL_STATE',
  OPERATION_ENABLED: 'OPERATION_ENABLED'
};

export const I18nKey = {
  MIND_MAP: 'MIND_MAP',
  OUTLINER: 'OUTLINER',
  COPY: 'COPY',
  PASTE: 'PASTE',
  DUPLICATE: 'DUPLICATE',
  DELETE: 'DELETE',

  CONFIRM: 'CONFIRM',
  CANCEL: 'CANCEL',
  REMOVE: 'REMOVE',
  RENAME: 'RENAME',
  DEFAULT: 'DEFAULT',
  SEARCH: 'SEARCH',
  BROWSE: 'BROWSE',
  CHOOSE_FILE: 'CHOOSE_FILE',

  LAYOUT: 'LAYOUT',
  LEFT_AND_RIGHT: 'LEFT_AND_RIGHT',
  ONLY_LEFT: 'ONLY_LEFT',
  ONLY_RIGHT: 'ONLY_RIGHT',

  ADD_SHEET: 'ADD_SHEET',
  SHEET: 'SHEET',

  EDIT: 'EDIT',
  PASTE_AS_PLAIN_TEXT: 'PASTE_AS_PLAIN_TEXT',
  PASTE_WITH_STYLE: 'PASTE_WITH_STYLE',
  ADD_SIBLING: 'ADD_SIBLING',
  ADD_CHILD: 'ADD_CHILD',
  EDIT_NOTES: 'EDIT_NOTES',
  REMOVE_NOTES: 'REMOVE_NOTES',
  CONVERT_TO_PLAIN_TEXT: 'CONVERT_TO_PLAIN_TEXT',
  SET_AS_EDITOR_ROOT: 'SET_AS_EDITOR_ROOT',
  EXPORT: 'EXPORT',
  EXPORT_TOPIC: 'EXPORT_TOPIC',
  EDIT_TOPOLOGY_DIAGRAM: 'EDIT_TOPOLOGY_DIAGRAM',
  SET_TOPIC_REFERENCES: 'SET_TOPIC_REFERENCES',
  INSERT_IMAGE: 'INSERT_IMAGE',
  //========================================
  TOPIC_STYLE: 'TOPIC_STYLE',
  STYLE: 'STYLE',
  TEXT_EDITOR: 'TEXT_EDITOR',
  LINK: 'LINK',
  LINK_TO_PARENT: 'LINK_TO_PARENT',
  SUB_LINKS: 'SUB_LINKS',
  COPY_STYLE: 'COPY_STYLE',
  PASTE_STYLE: 'PASTE_STYLE',
  CLEAR_TOPIC_STYLE: 'CLEAR_TOPIC_STYLE',
  CLEAR_ALL_CUSTOM_STYLE: 'CLEAR_ALL_CUSTOM_STYLE',
  LINE_TYPE: 'LINE_TYPE',
  //=======================================
  THEME: 'THEME',
  GLOBAL: 'GLOBAL',
  HIGHLIGHT: 'HIGHLIGHT',
  RANDOM_COLOR: 'RANDOM_COLOR',
  NORMAL_TOPIC: 'NORMAL_TOPIC',
  PRIMARY_TOPIC: 'PRIMARY_TOPIC',
  ROOT_TOPIC: 'ROOT_TOPIC',
  EXPORT_THEME: 'EXPORT_THEME',
  IMPORT_THEME: 'IMPORT_THEME',
  //=======================================
  TAGS: 'TAGS',
  TAGS_MANAGER: 'TAGS_MANAGER',
  TAG_NAME: 'TAG_NAME',
  ADD_TAG: 'ADD_TAG',
  UPDATE_TAG: 'UPDATE_TAG',
  ALREADY_ADDED: 'ALREADY_ADDED',
  CAN_BE_ADDED: 'CAN_BE_ADDED',
  TOPICS_THAT_USE_THIS_TAG: 'TOPICS_THAT_USE_THIS_TAG',
  //=======================================
  BACKGROUND: 'BACKGROUND',
  COLOR: 'COLOR',
  BORDER: 'BORDER',
  WIDTH: 'WIDTH',
  RADIUS: 'RADIUS',
  FONT_FAMILY: 'FONT_FAMILY',
  FONT_STYLE: 'FONT_STYLE',
  NORMAL: 'NORMAL',
  ITALIC: 'ITALIC',
  OBLIQUE: 'OBLIQUE',
  FONT_WEIGHT: 'FONT_WEIGHT',
  FONT_SIZE: 'FONT_SIZE',
  LINE_HEIGHT: 'LINE_HEIGHT',
  PADDING: 'PADDING',
  TOP: 'TOP',
  BOTTOM: 'BOTTOM',
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  NONE: 'NONE',
  SOLID: 'SOLID',
  DOTTED: 'DOTTED',
  DASHED: 'DASHED',
  DOUBLE: 'DOUBLE',

  ROUND: 'ROUND',
  CURVE: 'CURVE',
  LINE: 'LINE',

  COLLAPSE_ALL: 'COLLAPSE_ALL',
  EXPAND_ALL: 'EXPAND_ALL',
  CENTER_ROOT_TOPIC: 'CENTER_ROOT_TOPIC',
  ZOOM: 'ZOOM',
  ZOOM_IN: 'ZOOM_IN',
  ZOOM_OUT: 'ZOOM_OUT',
  RESET: 'RESET',
  RESET_ZOOM: 'RESET_ZOOM',

  NOTE_PLACEHOLDER: 'NOTE_PLACEHOLDER',

  TOPOLOGY_DIAGRAM_EDITOR: 'TOPOLOGY_DIAGRAM_EDITOR',
  BASIC: 'BASIC',
  FLOW_GRAPH: 'FLOW_GRAPH',
  ACTIVITY_DIAGRAM: 'ACTIVITY_DIAGRAM',
  SEQUENCE_DIAGRAM: 'SEQUENCE_DIAGRAM',
  CLASS_DIAGRAM: 'CLASS_DIAGRAM',

  REFERENCE_TOPICS: 'REFERENCE_TOPICS',
  REFERENCED_TOPICS: 'REFERENCED_TOPICS',
  GOTO_ORIGINAL_TOPIC: 'GOTO_ORIGINAL_TOPIC',

  INDENT: 'INDENT',
  OUTDENT: 'OUTDENT',
  PASTE_AND_SPLIT_BY_LINE_BREAK: 'PASTE_AND_SPLIT_BY_LINE_BREAK',

  SELECT_REF_TOPICS_TIP: 'SELECT_REF_TOPICS_TIP',
  TAG_NAME_OVER_MAX_TIP: 'TAG_NAME_OVER_MAX_TIP',
  DELETE_TAG_TIP: 'DELETE_TAG_TIP',
  DELETE_TOPOLOGY_TIP: 'DELETE_TOPOLOGY_TIP',
  DELETE_REFERENCE_TIP: 'DELETE_REFERENCE_TIP',
  FILE_FORMAT_ERROR: 'FILE_FORMAT_ERROR',

  SELECT_IMAGE_TIP1: 'SELECT_IMAGE_TIP1',
  SELECT_IMAGE_TIP2: 'SELECT_IMAGE_TIP2',
  SELECT_IMAGE_ERR_TIP: 'SELECT_IMAGE_ERR_TIP',

  HYPERLINK: 'HYPERLINK',
  INSERT_HYPERLINK: 'INSERT_HYPERLINK',

  SET_TO_ORIGINAL_SIZE: 'SET_TO_ORIGINAL_SIZE',
  MOVE_UP: 'MOVE_UP',
  MOVE_DOWN: 'MOVE_DOWN'
};

export const TempValueKey = {
  EDITOR_CONTENT: 'EDITOR_CONTENT'
};
