export const FOCUS_MODE_EDITING_TOPOLOGY = 'FOCUS_MODE_EDITING_TOPOLOGY';
export const OP_TYPE_START_EDITING_TOPOLOGY = 'OP_TYPE_START_EDITING_TOPOLOGY';
export const BLOCK_TYPE_TOPOLOGY = 'TOPOLOGY';
export const REF_KEY_TOPOLOGY_DIAGRAM = 'TOPOLOGY_DIAGRAM';
export const REF_KEY_TOPOLOGY_DIAGRAM_UTIL = 'TOPOLOGY_DIAGRAM_UTIL';

